FROM node:12.18.3

RUN npm install --global webpack jest typescript

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN npm install

RUN npm install --save-dev supertest

EXPOSE 8081

ENTRYPOINT [ "npm", "test" ]
